### ISSUE TITLE
PyTorch Implementation

### ISSUE THREAD

**Issue by LiyuanLucasLiu** [julian121266/RecurrentHighwayNetworks#16]
Hi I wonder is there any implementations of Recurrent Highway Network for PyTorch? Since lots of people are moving to PyTorch, it would be great if you guys can provide some "official" Recurrent Highway Network implementations for PyTorch :-)

**Comment by jzilly** [comment]
Hi LiyuanLucasLiu,
We currently do not have an implementation in PyTorch. Would definitely like to write the Recurrent Highway Code in PyTorch. Since I am quite busy this semester this is not likely to happen anytime soon though. Please do feel free to make a pull request if you want to implement RHNs in PyTorch.
